routes/routes.py
# myapp/front/routes/routes.py
from models.user import User
from models import storage
from flask import Blueprint, jsonify, render_template, request, session, redirect, url_for
from sqlalchemy.orm import scoped_session, sessionmaker
import hashlib
# Create a Blueprint instance
routes_bp = Blueprint('routes', __name__)

# Define route for login page


@routes_bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        # Get username and password from form
        username = request.form['username']
        password = request.form['password']
        hash_request_pwd = hashlib.sha256(password.encode()).hexdigest()
        # Check if username exists and password matches
        user = storage.authenticate("User", username, password)

        if user:

            if password == user.password:
                # Set session variable to indicate user is logged in
                session['logged_in'] = True
                session['username'] = username
                return redirect(url_for('routes.home'))
            else:
                return 'incorrect password'
        else:
            return 'Invalid username or password'
            # return user.__getattribute__(password)

    # If GET request, render login template
    return render_template('front/login.html')


@routes_bp.route('/logout', methods=['POST'])
def logout():
    session.pop('logged_in', None)
    session.pop('username', None)
    return redirect(url_for('routes.home'))


@routes_bp.route('/')
def home():
    # Check if user is logged in
    if 'logged_in' in session:
        return render_template("front/index.html")
    else:
        return redirect(url_for('routes.login'))


@routes_bp.route('/whatisquotes')
def whatisquotes():
    return render_template("front/whatisquotes.html")

templates/front/Signup.html
<!DOCTYPE html>
<html lang="en">

<head>
   <!-- basic -->
   <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <!-- mobile metas -->
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta name="viewport" content="initial-scale=1, maximum-scale=1">
   <!-- site metas -->
   <title>Quotes-signup</title>
   <meta name="keywords" content="">
   <meta name="description" content="">
   <meta name="author" content="">
   <!-- bootstrap css -->
   <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
   <!-- style css -->
   <link rel="stylesheet" type="text/css" href="css/style.css">
   <!-- Responsive-->
   <link rel="stylesheet" href="css/responsive.css">
   <!-- fevicon -->
   <link rel="icon" href="images/fevicon.png" type="image/gif" />
   <!-- Scrollbar Custom CSS -->
   <link rel="stylesheet" href="css/jquery.mCustomScrollbar.min.css">
   <!-- Tweaks for older IEs-->
   <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
   <!-- fonts -->
   <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700;900&family=Sen:wght@400;700;800&display=swap"
      rel="stylesheet">
   <!-- owl stylesheets -->
   <link rel="stylesheet" href="css/owl.carousel.min.css">
   <link rel="stylesheet" href="css/owl.theme.default.min.css">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css"
      media="screen">
   <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
</head>

<body>
   <!-- layout main section start -->
   <div class="container-fluid pl-0 pr-0">
      <div class="layout_main">
         <!-- banner section start -->
         <div class="banner_section">
            <div class="container">
               <div class="menu_main">
                  <div class="custome_menu">
                     <ul class="list-unstyled">
                        <li class="active"><a href="index.html">Home</a></li>
                        <li><a href="whatisquotes.html">what is quotes</a></li>
                        <li><a href="about.html">Our privacy</a></li>
                     </ul>
                  </div>
                  <div class="login_menu">
                     <div class="btn-group">
                        <a href="Login.html" class="btn btn-sm btn-outline-success">Login</a>
                     </div>
                  </div>
               </div>
            </div>
            <!-- testimonial section end -->
            <!-- contact section start -->
            <div class="contact_section layout_padding">
               <div class="container">
                  <div class="contact_section_2">
                     <div class="row">
                        <div class="col-md-12">
                           <h1 class="contact_taital mb-3">Sign Up</h1>
                           <form action="">
                              <div class="mail_section_1">
                                 <div class="btn-group text-left" role="group" aria-label="...">
                                    <button type="button" class="btn btn-outline-success" checked="">Mr</button>
                                    <button type="button" class="btn btn-outline-success">Ms</button>
                                 </div>
                                 <input type="text" class="mail_text" placeholder="Name" name="Name">
                                 <input type="text" class="mail_text" placeholder="Email" name="Email">
                                 <input type="date" class="mail_text" placeholder="Birthday" name="Birthday">
                                 <input type="password" class="pwd_text" placeholder="Password" name="Password">
                                 <input type="password" class="pwd_text" placeholder="confirm Password"
                                    name="cPassword">

                                 <div class="btn-block"><a href="#"
                                       class="btn btn-lg btn-outline-success float-left mt-3">Create new account</a>
                                 </div>
                              </div>
                           </form>
                           <hr>

                           </form>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- layout main section end -->
      <!-- copyright section start -->
      <div class="copyright_section">
         <div class="container">
            <p class="copyright_text">2024 All Rights Reserved</p>
         </div>
      </div>
      <!-- copyright section end -->
      <!-- Javascript files-->
      <script src="js/jquery.min.js"></script>
      <script src="js/popper.min.js"></script>
      <script src="js/bootstrap.bundle.min.js"></script>
      <script src="js/jquery-3.0.0.min.js"></script>
      <script src="js/plugin.js"></script>
      <!-- sidebar -->
      <script src="js/jquery.mCustomScrollbar.concat.min.js"></script>
      <script src="js/custom.js"></script>
      <!-- javascript -->
      <script src="js/owl.carousel.js"></script>
      <script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
      <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
      <script>
         function openNav() {
            document.getElementById("mySidenav").style.width = "100%";
         }

         function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
         }
      </script>
</body>

</html>

templates/front/index.html
<!DOCTYPE html>
<html lang="en">

<head>
   <!-- basic -->
   <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <!-- mobile metas -->
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta name="viewport" content="initial-scale=1, maximum-scale=1">
   <!-- site metas -->
   <title>Quotes</title>
   <meta name="keywords" content="">
   <meta name="description" content="">
   <meta name="author" content="">
   <!-- bootstrap css -->
   <link rel="stylesheet" type="text/css" href="../static/css/bootstrap.min.css">
   <!-- style css -->
   <link rel="stylesheet" type="text/css" href="../static/css/style.css">
   <!-- Responsive-->
   <link rel="stylesheet" href="../static/css/responsive.css">
   <!-- fevicon -->
   <link rel="icon" href="../static/images/fevicon.png" type="image/gif" />
   <!-- Scrollbar Custom CSS -->
   <link rel="stylesheet" href="../static/css/jquery.mCustomScrollbar.min.css">
   <!-- Tweaks for older IEs-->
   <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
   <!-- fonts -->
   <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700;900&family=Sen:wght@400;700;800&display=swap"
      rel="stylesheet">
   <!-- owl stylesheets -->
   <link rel="stylesheet" href="../static/css/owl.carousel.min.css">
   <link rel="stylesheet" href="../static/css/owl.theme.default.min.css">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css"
      media="screen">
   <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
</head>

<body>
   <!-- layout main section start -->
   <div class="container-fluid pl-0 pr-0">
      <div class="layout_main">
         <!-- banner section start -->
         <div class="banner_section">
            <div class="container">
               <div class="menu_main">
                  <div class="custome_menu">
                     <ul class="list-unstyled">
                        <li class="active"><a href="{{ url_for('routes.home') }}">Home</a></li>
                        <li><a href="{{ url_for('routes.whatisquotes') }}">what is quotes</a></li>
                        <li><a href="#">Our privacy</a></li>
                     </ul>
                  </div>
                  {% if 'logged_in' in session %}
                  <nav class="navbar navbar-expand-lg">
                     <div class="collapse navbar-collapse navbar-dark" id="navbarScroll">
                        <ul class="navbar-nav mr-auto my-2 my-lg-0 navbar-nav-scroll" >
                           <li class="nav-item">
                              <form action="{{ url_for('routes.logout') }}" method="post">
                                 <input class="btn btn-outline-success" type="submit" value="Logout">
                              </form>
                           </li>
                           <li class="nav-item dropdown">
                              <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown"
                                 aria-expanded="false">
                                 {{ session['username'] }}
                              </a>
                              <ul class="dropdown-menu">
                                 <li><a class="dropdown-item btn-success" href="#">Dashboard</a></li>
                                 <li><a class="dropdown-item btn-success" href="#">List quotes</a></li>
                                 <li>
                                    <hr class="dropdown-divider">
                                 </li>
                                 <li><a class="dropdown-item btn-success" href="#">Acount & settings</a></li>
                              </ul>
                           </li>
                        </ul>
                     </div>
                  </nav>

                  {% else %}
                  <div class="btn-group">
                     <a href="{{ url_for('Signup') }}" class="btn btn-sm btn-outline-success">Login</a>
                     <a href="{{ url_for('Signup') }}" class="btn btn-sm btn-success">Sign up</a>
                  </div>
                  {% endif %}
               </div>
            </div>
            <div id="main_slider" class="carousel slide" data-ride="carousel">
               <div class="carousel-inner">
                  <div class="carousel-item active">
                     <div class="container">
                        <div class="row">
                           <div class="col-md-12">
                              <h1 class="banner_taital">Find <span class="theme-color">quotes</span> in all subjects
                              </h1>
                              <div class="banner_main">
                                 <div class="dropdown">
                                    <button class="btn btn-secondary dropdown-toggle" type="button"
                                       id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true"
                                       aria-expanded="false">All Category
                                    </button>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                       <a class="dropdown-item" href="#">Action</a>
                                       <a class="dropdown-item" href="#">Another action</a>
                                       <a class="dropdown-item" href="#">Something else here</a>
                                    </div>
                                 </div>
                                 <div class="main">
                                    <!-- Another variation with a button -->
                                    <div class="input-group">
                                       <input type="text" class="form-control"
                                          placeholder="Find quotes in all subjects" />
                                       <div class="input-group-append">
                                          <button class="btn btn-secondary" type="button"
                                             style="background-color: #ffffff; border-color:#ffffff ">
                                             <i class="fa fa-search" style="color: #191919;"></i>
                                          </button>
                                       </div>
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
            <!-- banner section end -->
            <!-- service section start -->
            <div class="service_section mt-5 pt-3">
               <div class="container">
                  <div class="row">
                     <div class="col-sm-12">
                        <h1 class="service_taital">Quotes by category</h1>
                     </div>
                  </div>
                  <div class="service_section_2">
                     <div class="row">
                        <div class="col">
                           <div class="service_box">
                              <div class="breakfast_img"><img src="../static/images/9147383.png"></div>
                           </div>
                           <h4 class="breakfast_text">Tech</h4>
                        </div>
                        <div class="col">
                           <div class="service_box">
                              <div class="breakfast_img"><img src="../static/images/3365753.png"></div>
                           </div>
                           <h4 class="breakfast_text">Social</h4>
                        </div>
                        <div class="col">
                           <div class="service_box">
                              <div class="breakfast_img"><img src="../static/images/9185582.png"></div>
                           </div>
                           <h4 class="breakfast_text">Politic</h4>
                        </div>
                        <div class="col">
                           <div class="service_box">
                              <div class="breakfast_img"><img src="../static/images/3366753.png"></div>
                           </div>
                           <h4 class="breakfast_text">Science</h4>
                        </div>
                        <div class="col">
                           <div class="service_box">
                              <div class="breakfast_img"><img src="../static/images/7490587.png"></div>
                           </div>
                           <h4 class="breakfast_text">Global</h4>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
            <!-- service section end -->
            <!-- contact section start -->
            <div class="contact_section mt-5 pt-3">
               <div class="container">
                  <div class="contact_section_2">
                     <div class="row">
                        <div class="col-md-12">
                           <h1 class="contact_taital">Contact us</h1>
                           <form action="">
                              <div class="mail_section_1">
                                 <input type="text" class="mail_text" placeholder="Name" name="Name">
                                 <input type="text" class="mail_text" placeholder="Phone Number" name="Phone Number">
                                 <input type="text" class="mail_text" placeholder="Email" name="Email">
                                 <textarea class="massage-bt" placeholder="Massage" rows="5" id="comment"
                                    name="Massage"></textarea>
                                 <div class="btn-block"><a href="#"
                                       class="btn btn-lg btn-outline-success float-left">SEND</a></div>
                              </div>
                           </form>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- layout main section end -->
      <!-- copyright section start -->
      <div class="copyright_section">
         <div class="container">
            <p class="copyright_text">2024 All Rights Reserved</p>
         </div>
      </div>
      <!-- copyright section end -->
      <!-- Javascript files-->
      <script src="../static/js/jquery.min.js"></script>
      <script src="../static/js/popper.min.js"></script>
      <script src="../static/js/bootstrap.bundle.min.js"></script>
      <script src="../static/js/jquery-3.0.0.min.js"></script>
      <script src="../static/js/plugin.js"></script>
      <!-- sidebar -->
      <script src="../static/js/jquery.mCustomScrollbar.concat.min.js"></script>
      <script src="../static/js/custom.js"></script>
      <!-- javascript -->
      <script src="../static/js/owl.carousel.js"></script>
      <script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
      <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
      <script>
         function openNav() {
            document.getElementById("mySidenav").style.width = "100%";
         }

         function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
         }
      </script>
</body>

</html>

templates/front/whatisquotes.html
<!DOCTYPE html>
<html lang="en">

<head>
   <!-- basic -->
   <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <!-- mobile metas -->
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta name="viewport" content="initial-scale=1, maximum-scale=1">
   <!-- site metas -->
   <title>quotes-WIQ</title>
   <meta name="keywords" content="">
   <meta name="description" content="">
   <meta name="author" content="">
   <!-- bootstrap css -->
   <link rel="stylesheet" type="text/css" href="../static/css/bootstrap.min.css">
   <!-- style css -->
   <link rel="stylesheet" type="text/css" href="../static/css/style.css">
   <!-- Responsive-->
   <link rel="stylesheet" href="../static/css/responsive.css">
   <!-- fevicon -->
   <link rel="icon" href="../static/../static/images/fevicon.png" type="image/gif" />
   <!-- Scrollbar Custom CSS -->
   <link rel="stylesheet" href="../static/css/jquery.mCustomScrollbar.min.css">
   <!-- Tweaks for older IEs-->
   <link rel="stylesheet" href="../static/https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
   <!-- fonts -->
   <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700;900&family=Sen:wght@400;700;800&display=swap"
      rel="stylesheet">
   <!-- owl stylesheets -->
   <link rel="stylesheet" href="../static/css/owl.carousel.min.css">
   <link rel="stylesheet" href="../static/css/owl.theme.default.min.css">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css"
      media="screen">
   <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
</head>

<body>
   <!-- layout main section start -->
   <div class="container-fluid pl-0 pr-0">
      <div class="layout_main">
         <!-- banner section start -->
         <div class="banner_section">
            <div class="container">
               <div class="menu_main">
                  <div class="custome_menu">
                     <ul class="list-unstyled">
                        <li class="active"><a href="{{ url_for('routes.home') }}">Home</a></li>
                        <li><a href="{{ url_for('routes.whatisquotes') }}">what is quotes</a></li>
                        <li><a href="#">Our privacy</a></li>
                     </ul>
                  </div>
                  <div class="login_menu">
                     <div class="btn-group">
                        {% if 'logged_in' in session %}
                        <div class="custome_menu_2">
                           <ul class="list-unstyled">
                              <li><span class="">{{ session['username'] }}</span></li>
                              <li>
                                 <form action="{{ url_for('routes.logout') }}" method="post">
                                    <input class="btn btn-outline-success" type="submit" value="Logout">
                                 </form>
                              </li>
                           </ul>
                        </div>
                        {% else %}
                        <a href="{{ url_for('Signup') }}" class="btn btn-sm btn-outline-success">Login</a>
                        <a href="{{ url_for('Signup') }}" class="btn btn-sm btn-success">Sign up</a>
                        {% endif %}
                     </div>
                  </div>
               </div>
            </div>
            <!-- testimonial section end -->
            <!-- contact section start -->
            <div class="contact_section">
               <div class="container">
                  <div class="contact_section_2">
                     <div class="row">
                        <div class="col-md-12">
                           <h3 class="contact_taital mb-3">what you know about quotes</h3>

                           <div class="mail_section_1 text-left">
                              <p>At Quotes, our mission resonates with the hearts of readers worldwide: to unearth the
                                 essence of timeless wisdom encapsulated within the pages of books and to serve as a
                                 beacon guiding seekers of enlightenment through the vast expanse of literary
                                 brilliance.</p>

                              <p> One of the hallmarks of Quotes lies in its treasure trove of curated literary gems.
                                 Within our digital halls, seekers of profound insight can discover an abundance of
                                 thought-provoking excerpts, poignant passages, and eloquent expressions drawn from the
                                 annals of literary history. Whether you seek solace in the poetic verses of Rumi, the
                                 philosophical musings of Nietzsche, or the timeless wisdom of Jane Austen, Quotes
                                 offers a sanctuary where every soul can find resonance.</p>

                              <p>But Quotes is more than a mere repository of words; it is a sanctuary where readers can
                                 immerse themselves in the transformative power of literature. Imagine embarking on a
                                 journey of self-discovery through the timeless wisdom of literary masters, finding
                                 solace in the comforting embrace of familiar words, or uncovering newfound inspiration
                                 within the pages of a beloved book. Within the hallowed halls of Quotes, the
                                 possibilities are as limitless as the imagination itself.</p>

                              <p>In addition to serving as a haven for literary exploration, Quotes also empowers
                                 readers to share their own insights, reflections, and musings with a global community
                                 of fellow book lovers. Whether you're inspired to pen your own thoughts on a profound
                                 passage or eager to engage in spirited discussions about your favorite authors and
                                 works, Quotes provides a platform where every voice is welcomed and celebrated.</p>

                              <p>But perhaps the true magic of Quotes lies in its ability to transcend the boundaries of
                                 time and space, connecting readers across generations and continents through the shared
                                 language of literature. Whether you're seeking solace in the timeless words of
                                 Shakespeare, inspiration in the revolutionary ideas of Thoreau, or enlightenment in the
                                 spiritual teachings of the East, Quotes offers a bridge that spans the vast expanse of
                                 human thought and experience.</p>

                              <p> So, what are you waiting for? Join us on Quotes today and unlock a world of literary
                                 inspiration, wisdom, and connection. Whether you're seeking solace, enlightenment, or
                                 simply a moment of quiet reflection, you'll find it all and more within the hallowed
                                 halls of our digital sanctuary. Welcome to Quotes - where the wisdom of the ages
                                 awaits.</p>
                           </div>

                           <hr>

                           </form>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- layout main section end -->
      <!-- copyright section start -->
      <div class="copyright_section">
         <div class="container">
            <p class="copyright_text">2024 All Rights Reserved</p>
         </div>
      </div>
      <!-- copyright section end -->
      <!-- Javascript files-->
      <script src="js/jquery.min.js"></script>
      <script src="js/popper.min.js"></script>
      <script src="js/bootstrap.bundle.min.js"></script>
      <script src="js/jquery-3.0.0.min.js"></script>
      <script src="js/plugin.js"></script>
      <!-- sidebar -->
      <script src="js/jquery.mCustomScrollbar.concat.min.js"></script>
      <script src="js/custom.js"></script>
      <!-- javascript -->
      <script src="js/owl.carousel.js"></script>
      <script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
      <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
      <script>
         function openNav() {
            document.getElementById("mySidenav").style.width = "100%";
         }

         function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
         }
      </script>
</body>

</html>